### ISSUE TITLE
Step settings

### ISSUE THREAD

**Issue by amiika** [hisschemoller/JS-EPG#1]
Awesome project! I managed to create some beats, but would also like to use this to create some melody patterns. Do you have some examples on how to use Euclid FX to change the pitch and produce some melody?

I don't know if you take feature requests but here's an idea about assigning some MIDI commands to each step. Some kind of "Step settings" could pop up and you could assign MIDI pitch, note length (in steps), velocity etc. In this way you could also use these cycles to produce melodic patterns more easily:
![tempsnip](https://user-images.githubusercontent.com/1742231/55506729-d8756e80-565e-11e9-8e91-e4f746a14e71.png)

**Comment by hisschemoller** [comment]
Hi Amiika, thanks!
Yes, I agree it's a good addition to be able to create melodies. I have some ideas of how I want to proceed with that, but for the moment my first priority is to have a stable version of the app as it is, and well tested desktop versions. 
After that the next thing is to add a melody addition.

**Comment by hisschemoller** [comment]
Melody patterns are on my list for a future version, so I'll close the issue.
